### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by NahnahAJ** [NahnahAJ/Catalog-of-my-things#1]
- Link to [GitHub project](https://github.com/NahnahAJ/Catalog-of-my-things/projects/1)

- There are 3 people in our team.

- @NatanimA was assigned tasks for Team member 1
- @arabiu033 was assigned tasks for Team member 2
- @NahnahAJ was assigned tasks for Team member 3

**Comment by cynthiainga** [comment]
Hi @NahnahAJ  @NatanimA & @arabiu033, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] Setup correctly the Kanban board ✔️ 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
